import type { SiteContent } from "./types";

const mainValues = [
  {
    title: "마케팅",
    subtitle: "Marketing",
    description: "퍼포먼스·CPC·바이럴·SNS·오프라인까지, 데이터 기반 전략 수립과 실행",
    icon: "📊",
    gradient: "from-purple-500/20 to-blue-500/20",
  },
  {
    title: "자동화·개발",
    subtitle: "Automation & Development",
    description: "마케팅 자동화 도구 직접 개발(Python·JavaScript), 계측·리포팅·알림 자동화",
    icon: "⚙️",
    gradient: "from-blue-500/20 to-cyan-500/20",
  },
  {
    title: "게임",
    subtitle: "Game",
    description: "게임 제작 경험, 게임기획전문가 자격, 게임 콘테스트 입상",
    icon: "🎮",
    gradient: "from-cyan-500/20 to-green-500/20",
  },
];

const subValues = [
  {
    title: "AI 활용",
    subtitle: "AI Utilization",
    description: "시장의 AI 툴·에이전트를 업무 전반에 적극 활용",
    icon: "🤖",
  },
  {
    title: "팀 리더십",
    subtitle: "Team Leadership",
    description: "프로젝트 리드·팀 총괄 실무",
    icon: "👥",
  },
  {
    title: "글로벌",
    subtitle: "Global",
    description: "한국어·일본어·영어 커뮤니케이션",
    icon: "🌏",
  },
];

const timelineData = [
  {
    year: "2020",
    activities: [
      "2020 게임 콘테스트 입상",
      "2020 청소년 게임잼 디자인상",
      "TOWON 건축사무소 인턴",
      "Duoringgo 110",
    ],
  },
  {
    year: "2021",
    activities: [
      "2021 부산 인디커넥트 페스티벌",
      "게임기획전문가 자격 취득",
      "고등학교 졸업",
      "대학 입학",
      "HOIT Connect",
      "워드프로세서 자격 취득",
      "위즈아카데미 부동산 경매 과정 수료",
      "SBS아카데미 게임기획 과정 수료",
      "SBS아카데미 프로그래밍 과정 수료",
    ],
  },
  {
    year: "2022",
    activities: [
      "매일경제 테스트 우수",
      "한크부동산에듀 법인활용 투자과정 수료",
      "이화여자대학교 린스타트업 과정 수료",
      "서울대학교 창업과정 수료",
      "서울대학교 청소년심리학 과정 수료",
      "토바스튜디오 기획",
      "엠미팅아이",
      "About Meeting 사내이사",
      "샤에듀 창업",
    ],
  },
  {
    year: "2023",
    activities: [
      "C#과 Unity로 만드는 게임 개발 시리즈 수료",
      "UniTalk Studio 대표",
      "크리에이티브 토픽 협업",
      "Rich MZ 강사",
      "Mee'Bud 대표",
      "GREIT 학회장",
      "MS Academy 강사",
      "드림박스 주식회사 대표이사",
      "엄이친찍 프로젝트",
      "서울대학교 해동 스타트업 23기 수료",
      "라이프해킹스쿨 창업 부트캠프 수료",
      "라이프해킹스쿨 리더 스피치 수료",
      "라이프해킹스쿨 지식창업 과정 수료",
      "Online Project-Based Software Development Camp 수료",
      "창업동아리 스쿼드 개발자 파트 참여",
    ],
  },
  {
    year: "2024",
    activities: [
      "드림박스 주식회사 월매출 1000만 원 달성",
      "롯데칠성음료 마케팅 수주 및 집행",
      "오사카 니시나리구 에어비앤비 오픈",
      "창업학회 창공 회장",
      "FreeYourMind 이사직 수락",
      "NeonFlow Director 수락",
      "BridgeMarketing 대표이사 수락",
      "양양 DJ 페스티벌 행사 총괄",
      "KT&G 상상플래닛 멤버",
    ],
  },
  {
    year: "2025",
    activities: [
      "브릿지마케팅 상반기 매출 3500 달성",
      "주식회사 코버스 대표이사직 수주",
    ],
  },
];

const portfolioData = [
  // 사업 (Startup)
  {
    id: "korvus",
    title: "Korvus Inc",
    subtitle: "소프트웨어 공급/마케팅 법인",
    period: "",
    url: "",
    description: "소프트웨어 공급 및 마케팅 법인. 일본 시장 대상 솔루션 제공.",
    tech: ["소프트웨어 공급", "마케팅", "국제사업"],
    features: [
      "소프트웨어 공급 - 각종 솔루션 제공",
      "마케팅 - 종합 마케팅 서비스",
      "일본 사업 - 일본 시장 진출 준비",
    ],
    images: [
      "/portfolio/business/1. korvus inc/korvus_inc_1.jpg",
    ],
    category: "startup",
  },
  {
    id: "aboutmeeting",
    title: "AboutMeeting",
    subtitle: "어둠 속 소개팅 서비스",
    period: "약 1년 반",
    url: "https://swweetter.ai/",
    description: "서울대학교 창업 동아리에서 시작된 프로젝트. 영화 「어바웃 타임」에서 영감을 받은 어둠 속 소개팅 서비스. 마케팅, 기획, 매장 관리, 개발 등 모든 영역을 담당.",
    tech: ["마케팅", "기획", "매장 관리", "개발"],
    features: [
      "어둠 속 소개팅 콘셉트 - 영화 「어바웃 타임」 착안",
      "오프라인 매장 운영 - 약 1년 반 운영",
      "통합 운영 - 마케팅, 기획, 개발 전부 담당",
    ],
    images: [
      "/portfolio/business/2. AboutMeeting/KakaoTalk_20251209_040017657.jpg",
      "/portfolio/business/2. AboutMeeting/KakaoTalk_20251209_040110785.jpg",
    ],
    category: "startup",
  },
  {
    id: "bridgemarketing",
    title: "BridgeMarketing",
    subtitle: "랜딩페이지 제작 서비스",
    period: "",
    url: "",
    description: "한국/일본 기업 대상 랜딩페이지 제작 서비스.",
    tech: ["React", "Next.js", "Node.js", "Python", "FastAPI"],
    features: [
      "랜딩페이지 디자인 - 풀 커스터마이즈",
      "반응형 디자인 - 모바일 최적화",
      "SEO 최적화 - 검색엔진 대응",
      "애니메이션 - 인터랙티브 UI",
      "CMS 연동 - 간편한 콘텐츠 관리",
    ],
    achievements: [
      "자사 서비스로 운영 중",
      "한국/일본 기업 대상 랜딩페이지 제작",
      "10+ 프로젝트 완료",
    ],
    category: "startup",
  },
  {
    id: "imate",
    title: "iMate",
    subtitle: "AI 에이전트 서비스",
    period: "",
    url: "https://www.imate.site",
    description: "AI 에이전트 기반 고객 서비스 플랫폼.",
    tech: ["HTML5", "CSS3", "JavaScript", "TypeScript", "React", "Node.js", "Python", "LLM"],
    features: [
      "AI 챗봇 - LLM 기반 자동 응답 시스템",
      "고객 지원 - 24/7 자동 대응",
      "다국어 지원 - 한국어/일본어/영어",
    ],
    category: "startup",
  },
  {
    id: "greit",
    title: "GREIT",
    subtitle: "수도권 부동산 학회",
    period: "",
    url: "",
    description: "수도권(서울) 부동산 학회. 회장 및 메인 강사로 활동. 유명 한국 부동산 강사 초빙.",
    tech: ["교육", "부동산 투자"],
    features: [
      "회장 활동 - 학회 운영 및 관리",
      "메인 강사 - 부동산 투자 교육",
      "강사 초빙 - 유명 부동산 전문가 초대",
    ],
    images: [
      "/portfolio/business/8. GREIT/KakaoTalk_20251209_040748060.png",
      "/portfolio/business/8. GREIT/KakaoTalk_20251209_040919429.jpg",
    ],
    category: "startup",
  },
  {
    id: "airbnb-osaka",
    title: "에어비앤비 오사카 니시나리구",
    subtitle: "숙박시설 운영",
    period: "",
    url: "",
    description: "일본 오사카 니시나리구에 에어비앤비 물건 오픈. 투자금 1500만 원, 월매출 600만 원 달성.",
    tech: ["부동산 운영", "숙박시설 관리", "수익화"],
    achievements: [
      "투자금 1500만 원",
      "월매출 600만 원 달성",
    ],
    images: [
      "/portfolio/business/15. Airbnb大阪西成区/KakaoTalk_20251209_043150344.jpg",
      "/portfolio/business/15. Airbnb大阪西成区/KakaoTalk_20251209_043204777.jpg",
      "/portfolio/business/15. Airbnb大阪西成区/KakaoTalk_20251209_043215241.jpg",
      "/portfolio/business/15. Airbnb大阪西成区/KakaoTalk_20251209_043246749.jpg",
    ],
    category: "startup",
  },
  {
    id: "mmeetingai",
    title: "엠미팅아이",
    subtitle: "온라인 소개팅 서비스",
    period: "2주",
    url: "",
    description: "온라인 소개팅 서비스. 2주 운영 기간에 신청자 400명, 매출 300만 원(순이익률 99%)을 달성.",
    tech: ["온라인 매칭", "마케팅"],
    achievements: [
      "신청자 수 400명 달성",
      "매출 300만 원",
      "순이익률 99%",
    ],
    images: [
      "/portfolio/business/5. エムミーティングアイ/KakaoTalk_20251209_035929318.jpg",
    ],
    category: "startup",
  },
  {
    id: "unitalkstudio",
    title: "UnitalkStudio",
    subtitle: "유튜브 스튜디오",
    period: "2개월",
    url: "",
    description: "유튜브 콘텐츠 제작 스튜디오. 편집팀, 출연팀, 기획팀을 별도 운영. 2개월 MVP 운영.",
    tech: ["콘텐츠 제작", "팀 관리"],
    features: [
      "편집팀 - 영상 편집 전문",
      "출연팀 - 출연자 관리",
      "기획팀 - 콘텐츠 기획",
    ],
    images: [
      "/portfolio/business/7. UnitalkStudio/KakaoTalk_20251209_040645200.jpg",
      "/portfolio/business/7. UnitalkStudio/KakaoTalk_20251209_040717703.jpg",
    ],
    category: "startup",
  },
  {
    id: "meebud",
    title: "Mee'Bud",
    subtitle: "한일 소개팅 서비스",
    period: "1개월",
    url: "",
    description: "일본×한국 국제 소개팅 서비스. 1개월 MVP 운영.",
    tech: ["국제 매칭", "다국어 지원"],
    features: [
      "한일 매칭 - 국제 커플 탄생",
      "다국어 지원 - 일본어·한국어",
      "MVP 테스트 - 1개월 시험 운영",
    ],
    images: [
      "/portfolio/business/9. Mee'Bud/KakaoTalk_20251209_041309020.png",
      "/portfolio/business/9. Mee'Bud/introduce ジャパン.svg",
    ],
    category: "startup",
  },
  {
    id: "dreambox",
    title: "드림박스 주식회사",
    subtitle: "이커머스 최적화 솔루션",
    period: "3년",
    url: "",
    description: "한국 이커머스 플랫폼 「쿠팡」 상위노출 로직 개발. 웹 개발·SaaS·AI 에이전트 개발을 3년간 리드.",
    tech: ["SaaS", "AI Agent", "웹 개발", "이커머스 최적화"],
    features: [
      "쿠팡 최적화 - 상위노출 로직 개발",
      "SaaS 개발 - 이커머스 지원 툴",
      "AI 에이전트 - 자동화 솔루션",
    ],
    achievements: [
      "대표이사 3년 재직",
      "월매출 1000만 원 달성",
    ],
    images: [
      "/portfolio/business/10. ドリームボックス株式会社/사업자등록증 1 (2)_page-0001.jpg",
    ],
    category: "startup",
  },
  {
    id: "picmusic",
    title: "PicMusic",
    subtitle: "음원 랭킹 플랫폼",
    period: "",
    url: "",
    description: "인스타그램, 유튜브, 틱톡의 음원 랭킹을 크롤링해 보여주고, 상위노출에 유리한 음원을 찾아주는 서비스.",
    tech: ["Web Crawling", "Data Analytics", "React"],
    features: [
      "음원 랭킹 - 인스타그램, 유튜브, 틱톡 통합",
      "크롤링 기술 - 실시간 데이터 수집",
      "트렌드 분석 - 상위노출 최적화",
    ],
    category: "startup",
  },
  {
    id: "changgong",
    title: "창공",
    subtitle: "창업 동아리",
    period: "",
    url: "",
    description: "월 10만 원을 버는 것을 목표로 하는 창업 동아리. 회장 및 대표 강사로 활동.",
    tech: ["교육", "창업 지원"],
    features: [
      "회장 활동 - 동아리 운영 및 관리",
      "대표 강사 - 창업 교육",
      "목표 설정 - 월 10만 원 수익화",
    ],
    images: [
      "/portfolio/business/12. 創空/KakaoTalk_20251209_041655957.png",
      "/portfolio/business/12. 創空/KakaoTalk_20251209_042358184.jpg",
    ],
    category: "startup",
  },
  {
    id: "neonflow",
    title: "NeonFlow",
    subtitle: "HR 커뮤니티 협업",
    period: "",
    url: "",
    description: "한국 1위 HR 커뮤니티 「기고만장」과 협업. 기술력/마케팅과 HR 커뮤니티의 인적 자원으로 다양한 프로젝트 협업.",
    tech: ["HR Tech", "협업 프로젝트"],
    features: [
      "기고만장 협업 - 한국 1위 HR 커뮤니티",
      "기술력 제공 - 개발 및 마케팅",
      "프로젝트 협업 - 다양한 분야",
    ],
    category: "startup",
  },
  {
    id: "eunvo",
    title: "EunVo",
    subtitle: "웹사이트 외주 개발",
    period: "1개월",
    url: "",
    description: "웹사이트 외주 개발 사이트. 1개월 만에 매출 300만 원 달성.",
    tech: ["웹 개발", "외주 서비스"],
    achievements: [
      "1개월 매출 300만 원 달성",
    ],
    category: "startup",
  },

  // 개발 외주 (Development)
  {
    id: "eden",
    title: "Eden",
    subtitle: "웹 플랫폼",
    period: "1개월",
    url: "https://eden-world.net",
    description: "버추얼 유튜버를 위한 아바타 마켓플레이스.",
    tech: ["React", "NestJS", "AWS"],
    category: "development",
  },
  {
    id: "muko",
    title: "무고 (Muko)",
    subtitle: "대형 커뮤니티 사이트",
    period: "3개월",
    url: "https://muko.kr",
    description: "국내 영화 커뮤니티 사이트. 커뮤니티, 이벤트, 메시지, 출석, 공지 등의 기능을 제공. 월간 활성 사용자 약 30만 명.",
    tech: ["NextJS", "NestJS", "AWS", "ECS", "Docker"],
    features: [
      "커뮤니티 포럼 - 영화 리뷰, 토론, 정보 공유",
      "이벤트 관리 - 시사회, 프리미어 정보",
      "메시지 시스템 - 사용자 간 커뮤니케이션",
      "출석 체크 - 매일 로그인 리워드",
      "관리자 CMS - 콘텐츠 관리 시스템",
    ],
    achievements: [
      "MAU(월간 활성 사용자) 약 30만 명 달성",
      "1일 평균 10,000+ 방문자",
      "안정적인 ECS 인프라 운용",
    ],
    category: "development",
  },
  {
    id: "blueclub",
    title: "블루클럽 창업",
    subtitle: "홈페이지",
    period: "5일",
    url: "https://blueclub-changup.com",
    description: "블루클럽 창업 홈페이지. 랜딩페이지.",
    tech: ["React", "Next.js"],
    category: "development",
  },
  {
    id: "choonsim",
    title: "Choonsim",
    subtitle: "암호화폐 거래 플랫폼",
    period: "10일",
    url: "https://www.choonsim.com",
    description: "암호화폐 거래 플랫폼. 실시간 시세 조회, 거래, 차트 조회 기능.",
    tech: ["React", "Vite", "NestJS"],
    category: "development",
  },
  {
    id: "dutyfree",
    title: "DutyFree Price",
    subtitle: "웹 플랫폼 & PWA",
    period: "3일",
    url: "https://dutyfree-price.com",
    description: "면세점 상품 크롤링 가격 비교 서비스.",
    tech: ["React", "NestJS", "Python"],
    category: "development",
  },
  {
    id: "apex",
    title: "Apex",
    subtitle: "웹 플랫폼",
    period: "5일",
    url: "https://a-pex.co.kr",
    description: "영어 학습 자료 판매 플랫폼.",
    tech: ["React", "NestJS", "AWS"],
    category: "development",
  },
  {
    id: "podcaster",
    title: "Podcaster",
    subtitle: "웹앱 플랫폼",
    period: "1일",
    url: "https://podcaster.boltlab.co",
    description: "팟캐스트 플랫폼. AI 팟캐스트 생성, 개발.",
    tech: ["React", "JavaScript", "Node.js", "Python", "FastAPI", "LLM", "MongoDB"],
    category: "development",
  },
  {
    id: "universitystudio",
    title: "University Studio (dreambox inc)",
    subtitle: "대학 플랫폼",
    period: "",
    url: "https://universitystudio.co.kr",
    description: "대학생 대상 플랫폼 개발.",
    tech: ["HTML5", "CSS3", "TypeScript", "Vue.js", "Angular", "Node.js", "React", "Python", "FastAPI", "LLM", "MongoDB"],
    category: "development",
  },
  {
    id: "doctordrive",
    title: "Doctor Drive (BridgeMarketing)",
    subtitle: "의료 플랫폼",
    period: "",
    url: "https://doctordrive.vercel.app",
    description: "의료 정보 플랫폼.",
    tech: ["HTML5", "CSS3", "JavaScript", "Python", "LLM"],
    category: "development",
  },

  // 마케팅 외주 (Marketing)
  {
    id: "yangyang-dj",
    title: "양양 DJ 페스티벌",
    subtitle: "오프라인 행사 팀장",
    period: "",
    url: "",
    description: "양양 DJ 페스티벌의 오프라인 행사 팀장으로 기획 및 실행.",
    tech: ["행사 기획", "팀 관리", "오프라인 운영"],
    features: [
      "팀장 - 행사 전체 총괄",
      "오프라인 운영 - 현장 관리 및 실행",
    ],
    category: "marketing",
  },
  {
    id: "grandmasterclass",
    title: "GrandMasterClass",
    subtitle: "서울여자대학교 대형 강연",
    period: "",
    url: "https://www.instagram.com/grandmasterclass/",
    description: "서울여자대학교에서 진행한 대형 강연 행사 팀장.",
    tech: ["강연 기획", "행사 관리"],
    features: [
      "팀장 - 강연 행사 총괄",
      "대형 강연 - 서울여자대학교",
    ],
    category: "marketing",
  },
  {
    id: "musinsa",
    title: "MUSINSA STANDARD",
    subtitle: "패션 브랜드 마케팅",
    period: "",
    url: "",
    description: "한국 패션 플랫폼 「무신사 스탠다드」 마케팅 실행.",
    tech: ["패션 마케팅", "브랜딩"],
    category: "marketing",
  },
  {
    id: "lecosme",
    title: "루코스메",
    subtitle: "마케팅 대행",
    period: "",
    url: "",
    description: "한국 화장품 브랜드 「루코스메」의 마케팅 전략 수립 및 실행. SNS 마케팅, 인플루언서 마케팅, 온라인 광고 운용을 통해 브랜드 인지도 향상과 온라인 매출 증대를 달성.",
    tech: ["SNS 마케팅", "인플루언서 마케팅", "광고 운용"],
    features: [
      "SNS 전략 수립 - 인스타그램, 틱톡 활용",
      "인플루언서 협업 - 마이크로 인플루언서 활용",
      "광고 캠페인 - Meta 광고, Google 광고",
    ],
    category: "marketing",
  },
  {
    id: "medis-dental",
    title: "메디스치과",
    subtitle: "치과 마케팅",
    period: "",
    url: "",
    description: "메디스치과의 디지털 마케팅 전반을 담당. 로컬 SEO 최적화, 온라인 예약 시스템 연동, 리뷰 관리를 통해 신규 환자 유치 및 예약률 향상을 실현.",
    tech: ["로컬 SEO", "리뷰 마케팅", "예약 시스템 연동"],
    features: [
      "로컬 SEO 최적화 - 구글 비즈니스 프로필 운용",
      "리뷰 관리 - 리뷰 수집 및 대응",
      "온라인 예약 촉진 - 랜딩페이지 최적화",
    ],
    category: "marketing",
  },
  {
    id: "kia-event",
    title: "기아자동차 이벤트",
    subtitle: "자동차 이벤트 마케팅",
    period: "",
    url: "",
    description: "기아자동차의 신차 발표 행사 및 프로모션 이벤트 마케팅 기획 및 실행. 온·오프라인 통합 마케팅을 통해 높은 참여율과 브랜드 인게이지먼트를 달성.",
    tech: ["이벤트 마케팅", "O2O 마케팅", "SNS 프로모션"],
    features: [
      "이벤트 기획 - 신차 발표회, 시승 이벤트",
      "통합 마케팅 - 온라인 광고 + 오프라인 활동",
      "SNS 프로모션 - 실시간 콘텐츠 배포",
    ],
    category: "marketing",
  },
  {
    id: "codevmap",
    title: "CoDevMap",
    subtitle: "개발자 커뮤니티 마케팅",
    period: "",
    url: "",
    description: "개발자 대상 플랫폼 「CoDevMap」의 마케팅 전략 및 실행. 개발자 커뮤니티 활성화, 콘텐츠 마케팅, 기술 블로그 운영을 통해 사용자 확보 및 인게이지먼트 향상을 달성.",
    tech: ["콘텐츠 마케팅", "커뮤니티 마케팅", "기술 블로그"],
    features: [
      "커뮤니티 활성화 - 온라인 이벤트, 밋업 기획",
      "콘텐츠 제작 - 기술 블로그, 튜토리얼 영상",
      "SNS 운영 - 개발자 대상 SNS 채널 관리",
    ],
    category: "marketing",
  },
  {
    id: "gyeonggi-youth",
    title: "경기도 청년의 날 행사",
    subtitle: "공공 행사 마케팅",
    period: "",
    url: "",
    description: "경기도 주최 「청년의 날」 행사의 마케팅 기획 및 실행. 청년층을 타깃으로 한 SNS 캠페인, 인플루언서 협업, 오프라인 행사 연계를 통해 높은 참여율을 달성.",
    tech: ["이벤트 마케팅", "SNS 캠페인", "인플루언서 협업"],
    features: [
      "SNS 캠페인 - 인스타그램, 틱톡 챌린지",
      "인플루언서 협업 - 청년 인플루언서 활용",
      "오프라인 행사 - 부스 운영, 프로모션",
    ],
    category: "marketing",
  },
  {
    id: "snu-eye-clinic",
    title: "SNU안과",
    subtitle: "안과 마케팅",
    period: "",
    url: "",
    description: "SNU안과의 디지털 마케팅 전략 수립 및 실행. 로컬 SEO, 온라인 광고, 리뷰 마케팅을 통해 신규 환자 유치 및 브랜드 인지도 향상을 달성.",
    tech: ["로컬 SEO", "Google 광고", "리뷰 마케팅"],
    features: [
      "로컬 SEO 최적화 - 지역 검색 상위노출",
      "Google 광고 운용 - 검색 광고, 디스플레이 광고",
      "리뷰 관리 - 환자 리뷰 수집 및 대응",
    ],
    category: "marketing",
  },
  {
    id: "syaeducation",
    title: "SyaEducation",
    subtitle: "최상위권 대학 그룹 과외",
    period: "1개월",
    url: "",
    description: "최상위권 대학생에 의한 그룹 과외 서비스. 1개월 MVP 시험 운영.",
    tech: ["교육 서비스", "매칭 플랫폼"],
    features: [
      "최상위권 대학생 강사 - 서울대, 연세대, 고려대 등",
      "그룹 수업 - 효율적인 학습",
      "MVP 테스트 - 1개월 시험 운영",
    ],
    images: [
      "/portfolio/business/6. SyaEducation/KakaoTalk_20251209_035847643.png",
      "/portfolio/business/6. SyaEducation/KakaoTalk_20251209_035856370.png",
    ],
    category: "startup",
  },
  {
    id: "content-insight",
    title: "콘텐츠 인사이트",
    subtitle: "마케팅 대행",
    period: "",
    url: "",
    description: "콘텐츠 인사이트 마케팅 실행.",
    tech: ["콘텐츠 마케팅"],
    category: "marketing",
  },
  {
    id: "icatchyou",
    title: "아이캐치유",
    subtitle: "마케팅 대행",
    period: "",
    url: "",
    description: "아이캐치유 마케팅 실행.",
    tech: ["디지털 마케팅"],
    category: "marketing",
  },
  {
    id: "ecopeace",
    title: "에코피스 포럼",
    subtitle: "환경 포럼 마케팅",
    period: "",
    url: "",
    description: "에코피스 포럼 마케팅 실행.",
    tech: ["이벤트 마케팅", "환경"],
    category: "marketing",
  },
];

const categories = [
  { value: "all", label: "전체" },
  { value: "startup", label: "사업 실적" },
  { value: "development", label: "개발 실적" },
  { value: "marketing", label: "마케팅 실적" },
];

export const ko: SiteContent = {
  loading: {
    name: "정윤수",
  },
  hero: {
    name: "정윤수",
    romaji: "정윤수 | Jung Yunsu",
    role: "퍼포먼스 · 그로스 마케터",
    tagline: "움직이지 않으면, 아이디어는 그저 말일 뿐이다.",
    taglineEn: "Ideas mean nothing until they move.",
  },
  about: {
    heading: "마케터, 정윤수",
    paragraphs: [
      "한국에서 마케팅으로 커리어를 시작해, 3년간 직접 사업을 운영하며 퍼포먼스·바이럴·SNS 마케팅을 기획부터 실행·개선까지 일관되게 담당해왔습니다.",
      "Meta 등 운용형 광고와 CPC 캠페인, 오프라인 프로모션, 집객 동선 설계를 실무로 다뤘고, 마케팅을 지원하는 자동화 도구를 직접 개발(Python·JavaScript)해 계측과 개선 속도를 끌어올렸습니다.",
    ],
    closing:
      "한국어·일본어를 활용한 한일 마케팅이 가능하며, 어릴 때부터 게임을 만들고 즐겨온 사람으로서 게임업계에서 마케팅으로 기여하며 오래 성장하는 것이 목표입니다.",
    coreValuesTitle: "Core Values",
    mainValues,
    subValues,
  },
  works: {
    title: "Works & Journey",
    subtitle: "2020년부터 현재까지, 제가 걸어온 길",
    timeline: timelineData,
  },
  portfolio: {
    title: "Portfolio",
    subtitle: "사업 · 개발 · 마케팅 실적",
    categories,
    projects: portfolioData,
    showLess: "접기 ▲",
    showMore: (remaining: number) => `더 보기 (${remaining}+) ▼`,
  },
  card: {
    periodLabel: "기간:",
    techLabel: "기술 스택:",
    showDetail: "자세히 보기",
    hideDetail: "접기",
    imagesLabel: "프로젝트 이미지:",
    featuresLabel: "주요 기능:",
    achievementsLabel: "성과:",
    marketingNote:
      "*마케팅 포트폴리오는 보안 정책상 이미지를 첨부하지 않았습니다.",
  },
  connect: {
    title: "Let's Connect",
    subtitle: "커피 한잔 어떠세요?",
    ctaLabel: "📧 이메일로 연락하기",
    ctaUrl: "mailto:jys13230@gmail.com",
    ctaNote: "언제든 편하게 연락 주세요",
    socialHeading: "또는, 이쪽으로도",
    socialLinks: [
      {
        name: "Instagram",
        icon: "📸",
        url: "https://www.instagram.com/tei.youth/",
        description: "일상과 인사이트",
      },
      {
        name: "Email",
        icon: "📧",
        url: "mailto:jys13230@gmail.com",
        description: "직접 문의하기",
      },
    ],
    footerTagline: "움직이지 않으면, 아이디어는 그저 말일 뿐이다.",
    copyright: "© 2025 Jung Yunsu. All rights reserved.",
  },
};
